# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - booheaven

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.1

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Create production environment file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.production
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> .env.production
          echo "CLERK_ENCRYPTION_KEY=${{ secrets.CLERK_ENCRYPTION_KEY }}" >> .env.production
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env.production
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env.production
          echo "UPLOADTHING_TOKEN=${{ secrets.UPLOADTHING_TOKEN }}" >> .env.production
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_APP_URL=https://booheaven.azurewebsites.net" >> .env.production
          echo "NODE_ENV=production" >> .env.production

      - name: Create Azure deployment files
        run: |
          # Create a custom package.json for Azure deployment
          jq '.packageManager = undefined | .scripts.start = "node server.js" | .dependencies."next-view-transitions" = "0.3.4" | .resolutions = {"next-view-transitions": "0.3.4", "cmdk": "^1.0.0"}' package.json > azure-package.json
          
          # Create .npmrc to force installation
          echo "legacy-peer-deps=true" > .npmrc
          
          # Create custom server.js file for Azure
          cat > server.js << 'EOF'
          const { createServer } = require("http");
          const { parse } = require("url");
          const next = require("next");
          
          const dev = process.env.NODE_ENV !== "production";
          const hostname = "0.0.0.0";
          const port = process.env.PORT || 8080;
          
          const app = next({ dev, hostname, port });
          const handle = app.getRequestHandler();
          
          app.prepare().then(() => {
            createServer(async (req, res) => {
              try {
                const parsedUrl = parse(req.url, true);
                await handle(req, res, parsedUrl);
              } catch (err) {
                console.error("Error occurred handling", req.url, err);
                res.statusCode = 500;
                res.end("Internal Server Error");
              }
            })
              .once("error", (err) => {
                console.error(err);
                process.exit(1);
              })
              .listen(port, () => {
                console.log(`> Ready on http://${hostname}:${port}`);
              });
          });
          EOF
          
          # Create web.config for Azure App Service
          cat > web.config << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <webSocket enabled="false" />
              <handlers>
                <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
              </handlers>
              <rewrite>
                <rules>
                  <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
                    <match url="^server.js\/debug[\/]?" />
                  </rule>
                  <rule name="StaticContent">
                    <action type="Rewrite" url="public{REQUEST_URI}" />
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
                    </conditions>
                  </rule>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
                    </conditions>
                    <action type="Rewrite" url="server.js" />
                  </rule>
                </rules>
              </rewrite>
              <security>
                <requestFiltering>
                  <hiddenSegments>
                    <remove segment="bin" />
                  </hiddenSegments>
                </requestFiltering>
              </security>
              <httpErrors existingResponse="PassThrough" />
              <iisnode node_env="production" nodeProcessCommandLine="node.exe" />
            </system.webServer>
          </configuration>
          EOF

      - name: Install dependencies 
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js app
        run: pnpm build

      - name: Prepare deployment package
        run: |
          # Replace package.json with the Azure-optimized version
          mv azure-package.json package.json
          
          # Create startup command file
          echo "node server.js" > startup.txt

      - name: Zip artifact for deployment
        run: |
          # Include only necessary files
          zip -r release.zip .next package.json .npmrc server.js web.config startup.txt public node_modules

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3B7CD199C9A4924880BE0B5CFF2C423 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E8722865564A452EA976B56739877108 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F3001370065D4540B9D6221951892102 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'booheaven'
          slot-name: 'Production'
          package: .
